Repository edozo/mechanical-wombat, pull requests merged in 2019-12, with the labels that each got.

#18 Update README.md
  README.md
Labels: Ready for review 👀, 🚀 Approved 🚀

#17 Tech/knobs
  .storybook/addons.js
  README.md
  package.json
  src/Button/Button.stories.tsx
  src/Button/Button.styles.ts
  src/Button/Button.tsx
  yarn.lock
Labels: Ready for review 👀, 🚀 Approved 🚀

#19 Tech/button
  example/src/App.js
  src/Button/Button.stories.tsx
  src/Button/Button.styles.ts
  src/Button/Button.tsx
  src/defaultTheme.ts
  src/styled.d.ts
Labels: Ready for review 👀, 🚀 Approved 🚀

#20 Update approval_label.yml
  .github/workflows/approval_label.yml
Labels: Ready for review 👀, 🚀 Approved 🚀

#21 Change package name
  package.json
Labels: 🚀 Approved 🚀

#22 Tech/update deps
  .eslintrc.json
  package.json
  yarn.lock
Labels: 🚀 Approved 🚀

#23 Update package details
  package.json
Labels: 🚀 Approved 🚀

#24 Add example for .mdx with addons
  .storybook/config.js
  .storybook/presets.js
  package.json
  src/Button/Button.stories.mdx
  src/Button/Button.stories.tsx
  yarn.lock
Labels: Ready for review 👀, 🚀 Approved 🚀

#25 rename theme values and use aliases were possible
  src/TableDownloadButton/TableDownloadButton.styles.ts
  src/defaultTheme.ts
  src/styled.d.ts
Labels: Question ❔, 🚀 Approved 🚀

#26 add onclick to popover
  src/Popover/Popover.stories.tsx
  src/Popover/Popover.styles.ts
  src/Popover/Popover.tsx
Labels: Ready for review 👀, 🚀 Approved 🚀

#27 Bump package version
  package.json
Labels: Ready for review 👀

#29 Feature/google maps components
  README.md
  package.json
  src/Button/Button.stories.mdx
  src/List/List.stories.mdx
  src/List/List.styles.ts
  src/List/List.tsx
  src/List/ListItem.styles.ts
  src/List/ListItem.tsx
  src/List/index.tsx
  src/Popover/Popover.stories.mdx
  src/Popover/Popover.stories.tsx
  src/Popover/Popover.styles.ts
  src/Popover/Popover.tsx
  src/globalStyle.storybook.ts
  src/globalStyle.ts
Labels: Ready for review 👀, 🚀 Approved 🚀

#30 Feature/handle popover click
  .eslintrc.json
  src/Popover/Popover.stories.mdx
  src/Popover/Popover.tsx
  src/PopoverContent/PopoverContent.stories.mdx
  src/PopoverContent/PopoverContent.styles.ts
  src/PopoverContent/PopoverContent.tsx
  src/PopoverContent/index.tsx
  src/hooks/hooks.d.ts
  src/hooks/hooks.js
  src/hooks/index.js
  src/index.tsx
Labels: Ready for review 👀, 🚀 Approved 🚀

#32 Export forgotten components
  package.json
  src/index.tsx
Labels: Ready for review 👀
