Repository edozo/mechanical-wombat, pull requests merged in 2021-05, with the labels that each got.

#127 feature/add star
  package.json
  src/Icons/Icons.stories.tsx
  src/Icons/Icons.tsx
  src/Icons/icons/star-mark.svg
Labels: Ready for review 👀

#133 Bump lots of deps
  package.json
  playground/package.json
  playground/yarn.lock
  yarn.lock
Labels: 🚀 Approved 🚀

#136 Add CB to codeowners here too
  .github/CODEOWNERS
Labels: Ready for review 👀, 🚀 Approved 🚀

#135 feature/MAPS 1292 appcues launchpad
  package.json
  src/Icons/Icons.stories.tsx
  src/Icons/Icons.tsx
  src/Icons/icons/light-bulb.svg
Labels: Ready for review 👀, 🚀 Approved 🚀
