Repository edozo/mechanical-wombat, pull requests merged in 2022-01, with the labels that each got.

#171 Tech/fix icon
  package.json
  src/Icons/Icons.tsx
  src/Icons/icons/split-polygon.svg
Labels: 🚀 Approved 🚀, Ready for review 👀

#169 Global search
  package.json
  src/InputGroup/GlobalSearch.tsx
  src/InputGroup/InputGroup.stories.tsx
  src/InputGroup/InputGroup.styles.ts
  src/InputGroup/InputGroup.tsx
  src/InputGroup/index.ts
Labels: 🚀 Approved 🚀, Ready for review 👀

#174 Stop updating unmounted component
  package.json
  src/Collapse/Collapse.tsx
Labels: 🚀 Approved 🚀

#175 Export global search
  package.json
  src/index.tsx
Labels: 🚀 Approved 🚀

#167 Add new logo
  package.json
  src/EdozoLogo/edozo-logo.svg
Labels: 🚀 Approved 🚀, Ready for review 👀

#168 Add new blue and green
  package.json
  src/Theme/Colour.stories.tsx
  src/defaultTheme.ts
Labels: 🚀 Approved 🚀, Ready for review 👀

#173 change input component
  package.json
  src/InputGroup/Button/Button.styles.ts
  src/InputGroup/Button/Button.tsx
  src/InputGroup/Button/index.ts
  src/InputGroup/GlobalSearch.tsx
  src/InputGroup/Input/Input.styles.ts
  src/InputGroup/Input/Input.tsx
  src/InputGroup/Input/index.ts
  src/InputGroup/InputGroup.stories.tsx
  src/InputGroup/InputGroup.styles.ts
  src/InputGroup/InputGroup.tsx
  src/InputGroup/Item/Item.styles.ts
  src/InputGroup/Item/Item.tsx
  src/InputGroup/Item/index.ts
Labels: 🚀 Approved 🚀, Ready for review 👀

#179 Add eye and filter icons
  package.json
  src/Icons/Icons.stories.tsx
  src/Icons/Icons.tsx
  src/Icons/icons/eye.svg
  src/Icons/icons/filters.svg
Labels: 🚀 Approved 🚀

#176 Add new Edozo logo with colour and size attributes to wombat
  package.json
  src/EdozoLogo2/EdozoLogo2.stories.tsx
  src/EdozoLogo2/EdozoLogo2.tsx
  src/EdozoLogo2/edozo-logo.svg
  src/EdozoLogo2/help-centre-logo.svg
  src/EdozoLogo2/index.tsx
  src/EdozoLogo2/insight-logo.svg
  src/EdozoLogo2/maps-logo.svg
  src/EdozoLogo2/occupiers-logo.svg
  src/defaultTheme.ts
  src/index.tsx
  src/styled.d.ts
Labels: 🚀 Approved 🚀, Ready for review 👀

#181 Tech/header color
  package.json
  src/Header/Header.stories.tsx
  src/Menu/Menu.tsx
  src/Menu/MenuItem.styles.ts
  src/Menu/MenuItem.tsx
Labels: 🚀 Approved 🚀, Ready for review 👀

#182 Feature/new product switch
  package.json
  src/Badge/Badge.stories.tsx
  src/Badge/Badge.styles.ts
  src/Badge/Badge.tsx
  src/ButtonV2/ButtonV2.styles.ts
  src/ButtonV2/ButtonV2.tsx
  src/ButtonWithBadge/ButtonWithBadge.stories.tsx
  src/ButtonWithBadge/ButtonWithBadge.styles.ts
  src/ButtonWithBadge/ButtonWithBadge.tsx
  src/ButtonWithBadge/index.tsx
  src/EdozoLogo2/help-centre-logo.svg
  src/EdozoLogo2/insight-logo.svg
  src/EdozoLogo2/maps-logo.svg
  src/EdozoLogo2/occupiers-logo.svg
  src/Header/Header.stories.tsx
  src/Header/switch-app-icon-color.svg
  src/List/List.styles.ts
  src/List/ListItem.stories.tsx
  src/List/ListItem.styles.ts
  src/ProductSwitch/ProductSwitch.stories.tsx
  src/ProductSwitch/ProductSwitch.styles.ts
  src/ProductSwitch/ProductSwitch.tsx
  src/ProductSwitch/index.tsx
Labels: 🚀 Approved 🚀, Ready for review 👀

#183 added exports and icon story
  package.json
  src/Icons/Icons.stories.tsx
  src/Icons/Icons.tsx
  src/Icons/icons/switch-app-icon-color.svg
  src/index.tsx
Labels: 🚀 Approved 🚀

#186 Tech/fix positioning
  package.json
  src/ButtonWithBadge/ButtonWithBadge.styles.ts
  src/ButtonWithBadge/ButtonWithBadge.tsx
Labels: 🚀 Approved 🚀, Ready for review 👀

#185 Add breakpoints
  package.json
  src/DisplayBox/DisplayBox.styles.ts
  src/InputGroup/InputGroup.tsx
  src/defaultTheme.ts
  src/styled.d.ts
Labels: 🚀 Approved 🚀

#187 Add nested badge to button and restyle
  package.json
  src/ButtonV2/ButtonV2.stories.tsx
  src/ButtonV2/ButtonV2.styles.ts
  src/ButtonWithBadge/ButtonWithBadge.stories.tsx
  src/ButtonWithBadge/ButtonWithBadge.styles.ts
  src/ButtonWithBadge/ButtonWithBadge.tsx
  src/ButtonWithBadge/index.tsx
  src/Header/Header.stories.tsx
  src/List/ListItem.styles.ts
  src/ProductSwitch/ProductSwitch.stories.tsx
  src/ProductSwitch/ProductSwitch.styles.ts
  src/index.tsx
Labels: 🚀 Approved 🚀

#188 Tech/use context
  package.json
  src/Header/Header.stories.tsx
  src/List/List.stories.tsx
  src/List/List.styles.ts
  src/List/List.tsx
  src/List/ListItem.stories.tsx
  src/List/ListItem.styles.ts
  src/List/ListItem.tsx
  src/List/ListItem/ListItem.styles.ts
  src/List/ListItem/ListItem.tsx
  src/List/ListItem/index.tsx
  src/List/index.tsx
  src/Popover/Popover.stories.tsx
  src/Popover/Popover.styles.ts
  src/PopoverContent/PopoverContent.stories.tsx
  src/ProductSwitch/ProductSwitch.stories.tsx
Labels: 🙈 DO NOT REVIEW 🙈, 🚀 Approved 🚀
